### ISSUE TITLE
Please remove rider contact details from driver self-service portal until the driver has accepted the match

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#164] opened 2017-06-06 01:57 UTC
Currently, rider contact details are visible in the self-service portal before a drive has accepted a proposed match. These must only become visible once the driver has accepted the match.

**Comment by sasjkia** [comment] 2017-06-06 01:58
@dmilet @jkbits1 this is an urgent one. Is either of you free to take care of this tomorrow?

**Comment by dmilet** [comment] 2017-06-06 11:24
@jkbits1 I think this is on the front end code, selfservice.js, lines
496         $(listSelector).append('<li class="match-info-item">  rider phone - ' + val.driver_proposed_matches.RiderPhone + '</li>');
    497         $(listSelector).append('<li class="match-info-item">  rider email - ' + val.driver_proposed_matches.RiderEmail + '</li>');

Can you confirm and make the change? 
If I'm not mistaken, the change needs to be merged in order to take effect

**Comment by jkbits1** [comment] 2017-06-06 16:43
@sasjkia this is a duplicate of https://github.com/voteamerica/backend/issues/140 which was placed under review shortly after being created

**Closed** 2017-06-06 17:39 UTC
Labels: duplicate, high priority
