### ISSUE TITLE
Add a user-friendly message to the cancellation page

### ISSUE THREAD

**Issue by richardwestenra** [voteamerica/backend#75] opened 2016-10-27 09:51 UTC
I clicked the cancellation button in the email, and was directed to this page: https://api.carpoolvote.com/test/cancel-ride-request?UUID=b409c43a-b581-4a5c-831d-339c1783c8a9&RiderPhone=Westenra

Which just displayed the following text, completely unformatted: `{"rider_cancel_ride_request":""}`

Can we display something a little more user-friendly? At **minimum**, an `<h1>` saying something like "Your cancellation request has been received, thanks! You should receive an email shortly to confirm the cancellation." However ideally if we could display a proper HTML page, that'd go a long way. I can help with the design.

**Comment by jkbits1** [comment] 2016-10-27 13:40
@richardwestenra good points. I comment later about what we can do here

**Comment by jkbits1** [comment] 2016-10-27 15:45
@richardwestenra @dmilet  at the moment, the node app is returning the value from the db function that handles the request. I believe that an empty string is a success message. 

this part of the node app is used in a few places that I'm aware of, the email/sms links and the self-service page. The self service page takes the response and displays it in a status field. if we change the behaviour, all these things need to change and be synchronised when the change is deployed.

this is a relatively new part of the system. I'm open to changes although I am very busy elsewhere over the next day or two

**Comment by richardwestenra** [comment] 2016-11-07 16:53
@sasjkia has requested that we prioritise this issue. She's posted some details here: https://github.com/voteamerica/voteamerica.github.io/issues/228

Any chance that we could shift this a little? @jkbits1 @dmilet

**Comment by misteranderson** [comment] 2016-11-07 17:12
Instead of linking the user to that page/node endpoint directly, can we have a page that has JavaScript to make the request with jQuery / Ajax and returns a friendly message to the user?

**Comment by misteranderson** [comment] 2016-11-07 17:13
So, I guess, thinking in this static site way, send the user to /self-service/cancel-offer/?uuid=foo

**Comment by misteranderson** [comment] 2016-11-07 17:14
Or whatever pages would be required for each cancellation / pause use case.

**Comment by richardwestenra** [comment] 2016-11-07 19:20
@misteranderson That's a very good suggestion. I'd be tempted to just make it part of the self-service page, and listen for the `cancel-offer` query string key.

**Comment by dmilet** [comment] 2017-05-06 09:50
@richardwestenra @jkbits1 @sasjkia this is a duplicate of issue #72 
Can we close this one ?

**Comment by jkbits1** [comment] 2017-06-30 19:37
@dmilet agreed

**Closed by jkbits1** 2017-06-30 19:37 UTC
